resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
  ExternalNetworkVlanID: 905
  # Set to the router gateway on the external network
  ExternalInterfaceDefaultRoute: 10.0.0.250
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.1
  # The IP address of the EC2 metadata server. Generally the IP of the Undercloud
  EC2MetadataIp: 192.0.2.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["8.8.8.8","8.8.4.4"]
  # Set to "br-ex" if using floating IPs on native VLAN on bridge br-ex
  NeutronExternalNetworkBridge: "''"
  InternalApiNetworkVlanID: 901
  TenantNetworkVlanID: 902

  StorageMgmtNetworkVlanID: 904
  StorageMgmtNetCidr: 172.19.0.0/24
  StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  StorageNetworkVlanID: 903
  StorageNetCidr: 172.18.0.0/24
  StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]

  NetworkAdditional1NetCidr: '172.30.0.0/24'
  NetworkAdditional1NetworkVlanID: 910
  NetworkAdditional1AllocationPools: [{'start': '172.30.0.4', 'end': '172.30.0.250'}]
  NetworkAdditional2NetCidr: '172.31.0.0/24'
  NetworkAdditional2NetworkVlanID: 911
  NetworkAdditional2AllocationPools: [{'start': '172.31.0.4', 'end': '172.31.0.250'}]

#  AdditionalNetwork1VlanID: 910
#  AdditionalNetwork2VlanID: 911
#  AdditionalNetwork1NetCidr: 172.30.0.0/24
#  AdditionalNetwork2NetCidr: 172.31.0.0/24
#  AdditionalNetwork1AllocationPools: [{'start': '172.30.0.10', 'end': '172.30.0.200'}]
#  AdditionalNetwork2AllocationPools: [{'start': '172.31.0.10', 'end': '172.31.0.200'}]

#  SWIFT_PROXY_NAMES: "swift-node1 swift-node2 swift-node3"
#  SWIFT_PROXY_IPS: "172.19.0.101 172.19.0.102 172.19.0.103" 
#
  ExtraConfig:
    swift_proxy_node_ips:
      - "172.19.0.101"
      - "172.19.0.102"
      - "172.19.0.103"
